version: "3.8"

services:
    mysqlpayco:
        image: mysql:5.7
        expose:
            - 3306
        environment:
            MYSQL_DATABASE: "payco"
            MYSQL_ROOT_PASSWORD: "demo"
    soap:
        depends_on:
            - mysqlpayco
        build: ./soap/soap_pyco/
        command: gunicorn soap_pyco.wsgi:application --bind 0.0.0.0:8000 --workers=1
        networks:
            - default
        ports:
            - 7777:8000
        volumes:
            - ./soap/soap_pyco:/home/app/web
        environment:
            HOST: mysqlpayco
            NAME: "payco"
            USER: "root"
            PASSWORD: "demo"
            PORT: 3306
    api:
        environment:
            HOST: soap
            PORT: 8000
            URI: /soap/payco/?wsdl

        depends_on:
            - mysqlpayco
            - soap
        build: ./api_express
        volumes:
            - ./api_express/:/usr/src/app
        links:
            - soap:soap
        networks:
            - default
            - front
        ports:
            - 7474:7474

    nginx_react:
        build: ./frontend_react/
        networks:
            - front
        depends_on:
            - api
        ports:
            - 3001:80

networks:
    front:
        driver:
            bridge
         