version: "3.8"

services:
    mysqlpayco:
        image: mysql:5.7
        expose:
            - 3306

        environment:
            MYSQL_DATABASE: "payco"
            MYSQL_ROOT_PASSWORD: "demo"
    soap:
        depends_on:
            - mysqlpayco
        build: ./soap/soap_pyco/
        command: gunicorn soap_pyco.wsgi:application --bind 0.0.0.0:8000 --workers=1
        networks:
            - default
        ports:
            - 7777:8000
        volumes:
            - ./soap/soap_pyco:/home/app/web
        environment:
            HOST: mysqlpayco
            NAME: "payco"
            USER: "root"
            PASSWORD: "demo"
            PORT: 3306
    api:
        environment:
            HOST: soap
            PORT: 8000
            URI: /soap/payco/?wsdl

        depends_on:
            - mysqlpayco
            - soap
        build: ./api/project_api/
        volumes:
            - ./api/project_api/:/usr/src/app
        links:
            - soap:soap
        networks:
            - default
            - front
        ports:
            - 7474:7878

    front-react:
        build: ./frontend/
        depends_on:
               - api
        networks:
            - front
        volumes:
          - ./frontend:/usr/src/app
        # environment:
        #     HOST: api 
        #     PORT: 7878
        ports:
            - 3000:3000
networks:
    front:
        driver:
            bridge
         