  
FROM  node:alpine as build

WORKDIR "/usr/src/app"

COPY . .

RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent 
RUN npm run build

FROM nginx:1.16.0-alpine

WORKDIR "/usr/etc/nginx/"
COPY --from=build /usr/src/app/build /www/var/build
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d

#fire up nginx
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]
